FROM elixir:latest

# Install build dependencies
RUN apt-get update && \
    apt-get install -y build-essential inotify-tools

# Set up working directory
WORKDIR /app

# Install hex and rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# Install dependencies
COPY mix.* ./
RUN mix deps.get

# Copy the rest of the app
COPY . .

# Set the environment to development
ENV MIX_ENV=dev

# Expose port 4000
EXPOSE 4000

# Start the Phoenix app
CMD ["mix", "phx.server"]
